# Generated by Django 2.1.2 on 2018-11-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20181121_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
