# Generated by Django 2.1.2 on 2018-11-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='path',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
